#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Redirect any output to the journal (stderr)

set -e

exec 1>&2

cat >&${AGENT_COMFD} <<EOF
unset-env RESTART_WEBAPP
unset-env RESTART_WEBDAV
unset-env RESTART_Z_PUSH
EOF
