#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent

agent.unset_env("RESTART_WEBAPP")
agent.unset_env("RESTART_WEBDAV")
agent.unset_env("RESTART_Z_PUSH")
