#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
# Redirect any output to the journal (stderr)

set -e

exec 1>&2

systemctl --user start postgres

podman exec -i postgres sh -s <<'EOF'
query="SELECT EXISTS ( SELECT * FROM pg_tables WHERE schemaname = 'core' AND tablename  = 'settings');"
psql -q -U postgres webtop5 -tA -c "$query" 2> /dev/null | grep -q t
db_check=$?
c=10
while [ "$db_check" -ne 0 -o $c -eq 0 ]; do
  sleep 1s
  psql -q -U postgres webtop5 -tA -c "$query" 2> /dev/null  | grep -q t
  db_check=$?
  c=$(expr $c - 1 )
done
EOF
