#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

exec 1>&2 # Redirect any output to the journal (stderr)

# The postgres service requirement implicitly starts the whole pod.
# Note that:
# 1. systemctl blocks until postgres initialization completes.
# 2. if postgres init fails, we must explicitly stop the whole pod,
#    otherwise Systemd restarts it!
if ! systemctl --user -T start postgres.service ; then
   systemctl --user -T stop webtop
   exit 1
fi
