#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Redirect any output to the journal (stderr)

exec 1>&2

systemctl --user start webapp

curl -s -f "http://localhost:$TCP_PORT/webtop/api/com.sonicle.webtop.core/v1/admin/settings" \
  -H "Authorization: Bearer $WEBAPP_API_TOKEN" \
  -H 'accept: application/json'> /dev/null
webapp_check=$?
c=10
while [ "$webapp_check" -ne 0 -o $c -eq 0 ]; do
  sleep 1s
  curl -s -f "http://localhost:$TCP_PORT/webtop/api/com.sonicle.webtop.core/v1/admin/settings" \
    -H "Authorization: Bearer $WEBAPP_API_TOKEN" \
    -H 'accept: application/json' > /dev/null
  webapp_check=$?
  c=$(expr $c - 1 )
done
