#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent
import subprocess

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent_id = os.getenv("AGENT_ID", "")
if not agent_id:
    raise Exception("AGENT_ID not found inside the environemnt")

# Connect to redis
r = agent.redis_connect(privileged=True).pipeline()

restart_webapp = False
restart_webdav = False
restart_zpush = False

webtop_request_https_certificate = os.environ["WEBTOP_REQUEST_HTTPS_CERTIFICATE"].lower() in ('true', '1', 't')
if data.get("request_https_certificate") is not None:
    if data.get("request_https_certificate") != webtop_request_https_certificate:
        webtop_request_https_certificate = data["request_https_certificate"]
        agent.set_env("WEBTOP_REQUEST_HTTPS_CERTIFICATE", data["request_https_certificate"])

# Configure Traefik to route WebTop's host requests to the webtop module
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': True,
        'lets_encrypt': webtop_request_https_certificate,
        'host': data["hostname"],
    },
)
# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)

if data["hostname"] != os.getenv("WEBTOP_HOSTNAME"):

    public_url = 'https://' + data["hostname"] + '/webtop'
    dav_url = 'https://' + data["hostname"] + '/webtop-dav/server.php'

    with subprocess.Popen(['podman', 'exec', '-i', 'postgres', 'psql', '-U', 'postgres', 'webtop5'], stdin=subprocess.PIPE, text=True) as psql:
        print("DELETE FROM \"core\".\"settings\" WHERE service_id = 'com.sonicle.webtop.core' and key = 'public.url';\n", file=psql.stdin)
        print("INSERT INTO \"core\".\"settings\" (\"service_id\", \"key\", \"value\") VALUES ('com.sonicle.webtop.core', 'public.url', \'" + public_url + "\');\n", file=psql.stdin)

        print("DELETE FROM \"core\".\"settings\" WHERE service_id = 'com.sonicle.webtop.core' and key = 'davserver.url';\n", file=psql.stdin)
        print("INSERT INTO \"core\".\"settings\" (\"service_id\", \"key\", \"value\") VALUES ('com.sonicle.webtop.core', 'davserver.url',\'" + dav_url + "\');\n", file=psql.stdin)

    agent.assert_exp(psql.returncode == 0) # check the command is succesfull

    agent.set_env("WEBTOP_HOSTNAME", data["hostname"])
    restart_webapp = True

if "locale" in data and data["locale"] != os.environ["WEBTOP_LOCALE"]:

    locales = {
            'it_IT': {
                'LANGUAGE': 'it_IT',
                'START_DAY': '1',
                'DATE_FORMAT_LONG': 'dd MMM yyyy',
                'DATE_FORMAT_SHORT': 'dd/MM/yyyy',
                'TIME_FORMAT_SHORT': 'HH:mm',
                'TIME_FORMAT_LONG': 'HH:mm:ss',
                },
            'en_US': {
                'LANGUAGE': 'en_EN',
                'START_DAY': '0',
                'DATE_FORMAT_LONG': 'MMM dd, yyyy',
                'DATE_FORMAT_SHORT': 'MM/dd/yy',
                'TIME_FORMAT_SHORT': 'h:mm a',
                'TIME_FORMAT_LONG': 'h:mm:ss a',
                },
            'de_DE': {
                'LANGUAGE': 'de_DE',
                'START_DAY': '1',
                'DATE_FORMAT_LONG': 'dd MMM yyyy',
                'DATE_FORMAT_SHORT': 'dd.MM.yyyy',
                'TIME_FORMAT_SHORT': 'HH:mm',
                'TIME_FORMAT_LONG': 'HH:mm:ss',
                },
            'es_ES': {
                'LANGUAGE': 'es_ES',
                'START_DAY': '1',
                'DATE_FORMAT_LONG': 'dd. MMM yyyy.',
                'DATE_FORMAT_SHORT': 'd/M/yy',
                'TIME_FORMAT_SHORT': 'HH:mm',
                'TIME_FORMAT_LONG': 'HH:mm:ss',
                },
            'hr_HR': {
                'LANGUAGE': 'hr_HR',
                'START_DAY': '1',
                'DATE_FORMAT_LONG': 'dd. MMM yyyy.',
                'DATE_FORMAT_SHORT': 'dd. MM. yyyy.',
                'TIME_FORMAT_SHORT': 'HH:mm',
                'TIME_FORMAT_LONG': 'HH:mm:ss',
                },
            'hu_HU': {
                'LANGUAGE': 'hu_HU',
                'START_DAY': '1',
                'DATE_FORMAT_LONG': 'yyyy. MMMM dd.',
                'DATE_FORMAT_SHORT': 'yyyy.MM.dd.',
                'TIME_FORMAT_SHORT': 'HH:mm',
                'TIME_FORMAT_LONG': 'HH:mm:ss',
                },
            'fr_FR': {
                'LANGUAGE': 'fr_FR',
                'START_DAY': '1',
                'DATE_FORMAT_LONG': 'dd MMM yyyy',
                'DATE_FORMAT_SHORT': 'dd/MM/yyyy',
                'TIME_FORMAT_SHORT': 'HH:mm',
                'TIME_FORMAT_LONG': 'HH:mm:ss',
                }
            }

    with subprocess.Popen(['podman', 'exec', '-i', 'postgres', 'psql', '-U', 'postgres', 'webtop5'], stdin=subprocess.PIPE, text=True) as psql:
        print("DELETE FROM core.settings WHERE service_id = 'com.sonicle.webtop.core' and key = 'default.i18n.languageTag';\n", file=psql.stdin)
        print("DELETE FROM core.settings WHERE service_id = 'com.sonicle.webtop.core' and key = 'default.i18n.startDay';\n", file=psql.stdin)
        print("DELETE FROM core.settings WHERE service_id = 'com.sonicle.webtop.core' and key = 'default.i18n.format.date.short';\n", file=psql.stdin)
        print("DELETE FROM core.settings WHERE service_id = 'com.sonicle.webtop.core' and key = 'default.i18n.format.date.long';\n", file=psql.stdin)
        print("DELETE FROM core.settings WHERE service_id = 'com.sonicle.webtop.core' and key = 'default.i18n.format.time.short';\n", file=psql.stdin)
        print("DELETE FROM core.settings WHERE service_id = 'com.sonicle.webtop.core' and key = 'default.i18n.format.time.long';\n", file=psql.stdin)

        print("INSERT INTO core.settings (service_id, key, value) VALUES ('com.sonicle.webtop.core', 'default.i18n.languageTag', '"  + locales[data['locale']]['LANGUAGE'] + "');\n", file=psql.stdin)
        print("INSERT INTO core.settings (service_id, key, value) VALUES ('com.sonicle.webtop.core', 'default.i18n.startDay', '" + locales[data['locale']]['START_DAY']+ "');\n", file=psql.stdin)
        print("INSERT INTO core.settings (service_id, key, value) VALUES ('com.sonicle.webtop.core', 'default.i18n.format.date.short', '" + locales[data['locale']]['DATE_FORMAT_SHORT'] + "');\n", file=psql.stdin)
        print("INSERT INTO core.settings (service_id, key, value) VALUES ('com.sonicle.webtop.core', 'default.i18n.format.date.long', '" + locales[data['locale']]['DATE_FORMAT_LONG'] + "');\n", file=psql.stdin)
        print("INSERT INTO core.settings (service_id, key, value) VALUES ('com.sonicle.webtop.core', 'default.i18n.format.time.short', '" + locales[data['locale']]['TIME_FORMAT_SHORT'] + "');\n", file=psql.stdin)
        print("INSERT INTO core.settings (service_id, key, value) VALUES ('com.sonicle.webtop.core', 'default.i18n.format.time.long', '" + locales[data['locale']]['TIME_FORMAT_LONG'] + "');\n", file=psql.stdin)

    agent.assert_exp(psql.returncode == 0) # check the command is succesfull

    agent.set_env("WEBTOP_LOCALE", data["locale"])
    restart_webapp = True

if "timezone" in data and data["timezone"] != os.environ["WEBTOP_TIMEZONE"]:
    with subprocess.Popen(['podman', 'exec', '-i', 'postgres', 'psql', '-U', 'postgres', 'webtop5'], stdin=subprocess.PIPE, text=True) as psql:
        print("DELETE FROM core.settings WHERE service_id = 'com.sonicle.webtop.core' and key = 'default.i18n.timezone';\n", file=psql.stdin)
        print("INSERT INTO core.settings (service_id, key, value) VALUES ('com.sonicle.webtop.core', 'default.i18n.timezone','" + data["timezone"] + "');\n", file=psql.stdin)

    agent.assert_exp(psql.returncode == 0) # check the command is succesfull

    agent.set_env("WEBTOP_HOSTNAME", data["hostname"])
    restart_webapp = True
    restart_webdav = True
    restart_zpush = True

agent.dump_env()

if restart_webapp:
    agent.run_helper("systemctl", "--user", "restart", "webapp").check_returncode()

if restart_webdav:
   agent.run_helper("systemctl", "--user", "restart", "webdav").check_returncode()

if restart_zpush:
    agent.run_helper("systemctl", "--user", "restart", "z-push").check_returncode()
