#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

exec 1>&2 # Send any output to stderr, to not alter the action response protocol

cat >&${AGENT_COMFD} <<EOF
set-env WEBTOP_TIMEZONE Etc/UTC
set-env WEBTOP_LOCALE en_US
set-env WEBTOP_REQUEST_HTTPS_CERTIFICATE False
set-env WEBDAV_DEBUG True
set-env WEBDAV_LOG_LEVEL DEBUG
set-env Z_PUSH_LOG_LEVEL DEBUG
set-env Z_PUSH_IMAP_SERVER 10.5.4.1
set-env Z_PUSH_USE_LEGACY_FOLDER_IDS false
set-env WEBAPP_JS_DEBUG false
set-env WEBAPP_MIN_MEMORY 512
set-env WEBAPP_MAX_MEMORY 1024
dump-env
EOF
