#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import string
import secrets

try:
    webapp_env = agent.read_envfile("webapp.env")
except FileNotFoundError:
    # Generate a new API token, for webtop.properties expansion
    alphabet = string.ascii_letters + string.digits
    api_token = ''.join([secrets.choice(alphabet) for i in range(32)])
    webapp_env = {
        "WEBAPP_API_TOKEN": api_token,
    }
    agent.write_envfile("webapp.env", webapp_env)
