#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import agent
import agent.tasks
import os

request = json.load(sys.stdin)

# Configure Traefik to route "/webtop" path requests to the webapp service
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': True,
        'lets_encrypt': False,
        'path': '/webtop',
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)


# Configure Traefik to route "/webtop-dav" path requests to the webdav service
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': f"{os.environ['MODULE_ID']}-webdav",
        'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': True,
        'lets_encrypt': False,
        'path': '/webtop-dav',
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)

response = agent.tasks.runp_brief([{
    "agent_id": agent.resolve_agent_id('traefik@node'),
    "action": "set-route",
    "data": {
        'instance': f"{os.environ['MODULE_ID']}-well-known-caldav",
        'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': True,
        'lets_encrypt': False,
        'path': '/.well-known/caldav',
    }},{
    "agent_id": agent.resolve_agent_id('traefik@node'),
    "action": "set-route",
    "data": {
        'instance': f"{os.environ['MODULE_ID']}-well-known-carddav",
        'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': True,
        'lets_encrypt': False,
        'path': '/.well-known/carddav',
    }}]
)
