#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import os
import webtop
import agent

event_input = json.load(sys.stdin)

if event_input['module_uuid'] == os.getenv('EJABBERD_MODULE_UUID'):
    # We need to set the NEW EJABBERD_MODULE env variable to configure the module
    agent.set_env('EJABBERD_MODULE', event_input['module_id'])
    webtop.configure_module(os.getenv('MAIL_MODULE'), os.environ) # Ignore exit code
