#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

path = './legacy_ids_enabled'
check_file = os.path.exists(path)

# Check if the migrated z-push state use the legacy folder ids format
if check_file:
    agent.set_env('Z_PUSH_USE_LEGACY_FOLDER_IDS', 'True')
    os.remove(path)
