#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os

timezone = os.getenv("WEBTOP_TIMEZONE")
log_level = os.getenv("Z_PUSH_LOG_LEVEL")
imap_server = os.getenv("Z_PUSH_IMAP_SERVER")
use_legacy_folder_ids = os.getenv("Z_PUSH_USE_LEGACY_FOLDER_IDS", 'False').lower() in ('true', '1', 't')

config={
        "timezone": f"{timezone}",
        "log": {
            "level": f"{log_level}",
            "dir": "/var/log/z-push/"
            },
        "mail": {
            "imapServer": f"{imap_server}"
            },
        "webtop": {
            "apiBaseUrl": "http://localhost:8080/webtop"
            },
        "state": {
            "useLegacyFolderIds": use_legacy_folder_ids,
            "dir": "/var/log/z-push/state"
            }
        }

with open('z-push_config.json', 'w') as f:
    json.dump(config, f)
