#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

cat <<EOF > webtop.properties
webtop.log.target=console
webtop.session.forcesecurecookie=true
webtop.js.debug=$WEBAPP_JS_DEBUG
webtop.home=/var/lib/nethserver/webtop
EOF
