#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import os

timezone = os.getenv("WEBTOP_TIMEZONE")
log_level = os.getenv("Z_PUSH_LOG_LEVEL")
imap_server = os.getenv("Z_PUSH_IMAP_SERVER")
use_legacy_folder_ids = os.getenv("Z_PUSH_USE_LEGACY_FOLDER_IDS", 'False').lower() in ('true', '1', 't')

config={
        "timezone": f"{timezone}",
        "log": {
            "level": f"{log_level}",
            "dir": "/var/log/z-push/"
            },
        "mail": {
            "imapServer": f"{imap_server}"
            },
        "webtop": {
            "apiBaseUrl": "http://localhost:8080/webtop"
            },
        "state": {
            "useLegacyFolderIds": use_legacy_folder_ids,
            "dir": "/var/log/z-push/state"
            }
        }

with open('z-push_config.json', 'w') as f:
    json.dump(config, f)
