#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

source webapp.env

cat <<EOF > webtop.properties
webtop.log.target=console
webtop.session.forcesecurecookie=true
webtop.js.debug=$WEBAPP_JS_DEBUG
webtop.home=/var/lib/nethserver/webtop
webtop.provisioning.api.token=$WEBAPP_API_TOKEN
webtop.mailbridge.smtp.host=127.0.0.1
webtop.mailbridge.smtp.port=10125
webtop.mailbridge.smtp.auth=true
EOF
