#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Symlinked by actions:
# - clone-module
# - restore-module

import sys
import json
import agent

request = json.load(sys.stdin)
agent.set_env('MAIL_MODULE_UUID', request['environment']['MAIL_MODULE_UUID'])
agent.set_env('Z_PUSH_USE_LEGACY_FOLDER_IDS', request['environment']['Z_PUSH_USE_LEGACY_FOLDER_IDS'])
