#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import os
import webtop

event_input = json.load(sys.stdin)

if (event_input['module_uuid'] == os.getenv('MAIL_MODULE_UUID'):
    webtop.configure_module(event_input['module_id'], os.environ) # Ignore exit code
